global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'order-service:8081', 'product-service:8082', 'user-service:8083']
