server:
  port: 8080

spring:
  profiles:
    include: route
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
