server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: api-gateway
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
